#!/bin/bash

## atualização
sudo pacman -Syu

## pacman
sudo pacman -S gnome-tweaks gnome-usage evolution transmission-gtk

## flatpak
flatpak install flathub com.spotify.Client
flatpak install flathub org.libreoffice.LibreOffice
flatpak install flathub com.discordapp.Discord

## AUR
yay -S google-chrome

## snap
sudo snap install code --classic

